server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SH
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
#      discovery:
#        cluster-name: HZ
mybatis:
  type-aliases-package: com.zhang.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.zhang: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka服务注册
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#pattern:
#  name: 本地环境local